### ISSUE TITLE
Divide up tex file

### ISSUE THREAD

**Issue by cheymans** [aamon/i-band-technical#2]
Morning again!

Git is very good at merging conflicts, but it's not 100% reliable.  It's therefore a good idea to split up long files into smaller ones - so that we're not simultaneously working on the same file.

eg
\section{Introduction}
\input(introduction.tex}

\section{Results}
\input{results.tex}

and introduction.tex and results.tex are a separate file with the text in them.

Have a look at Cross-catalogue_comparisons.tex for an example
@aamon can you take this on?

**Comment by aamon** [comment]
Done!
